export const TYPEFACE_STYLES = [
    "Serif",
    "Sans serif",
    "Slab serif",
    "Script",
    "Stylized",
    "Quirky",
    "Other",
];
export const LETTERING_ONTOLOGIES = [
    "Printed",
    "Decal",
    "Painted",
    "Pan channel",
    "Pan face",
    "Handmade",
    "Embossed",
    "Debossed",
    "Pen or marker",
    "Reader board",
    "Spray paint",
    "LED",
    "Other electronic",
    "Neon",
    "Tile",
    "Chalk",
    "House number",
    "Ghost sign",
];
export const PLACEMENTS = [
    "Window-stuck",
    "Window-placed",
    "Awning/canopy",
    "Blade",
    "Fascia",
    "Marquee",
    "Hanging",
    "Name-plate",
    "Painted wall",
    "Freestanding",
    "Parapet",
    "Ground",
    "Bench",
    "Flag",
    "Pole-mounted",
    "Post and panel",
    "Pylon",
    "Banner",
    "Wall-placed",
    "Wall-stuck",
    "Other-stuck",
    "Snipe",
    "Graffiti",
    "Infrastructure",
    "Memorial",
    "Sticker",
    "Other",
];
export const FILTER_TYPES = [
    { value: "municipality", label: "Municipality" },
    { value: "initials", label: "Initials" },
];

export const MY_PHOTOS_FILTER_TYPES = [
    { value: "municipality", label: "Municipality" },
    { value: "status", label: "Status" },
];

export const MESSAGE_FUNCTIONS = [
    "Identification",
    "Address",
    "Joint tenant",
    "Operational information",
    "Advisement/regulation",
    "Directory",
    "Generic information",
    "Menu of options",
    "Commemoration",
    "Street name",
    "Advertisement",
    "Wayfinding",
    "Infrastructure",
    "Covid-related",
    "Other",
];
